#!/usr/bin/env bash
# Write a .env file with port assignments shifted by OFFSET from the defaults.
# Usage: write-ports-env.sh <offset>
set -euo pipefail

OFFSET="${1:?offset required}"

if ! [[ "$OFFSET" =~ ^[0-9]+$ ]]; then
  printf "Error: OFFSET must be a non-negative integer, got: %s\n" "$OFFSET" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$REPO_ROOT/.env"

cat > "$ENV_FILE" <<EOF
# Port offset: +${OFFSET} from defaults. Generated by: make port-offset OFFSET=${OFFSET}
# Run 'make reset-ports' to restore defaults, or 'make clean' to reset and wipe data.
YB_MASTER_UI_PORT=$((7000 + OFFSET))
YB_TSERVER_UI_PORT=$((9000 + OFFSET))
YB_YSQL_PORT=$((5433 + OFFSET))
YB_MASTER_RPC_PORT=$((7100 + OFFSET))
YB_TSERVER_RPC_PORT=$((9100 + OFFSET))
YB_YB_UI_PORT=$((15433 + OFFSET))
EOF

printf "Wrote %s\n" "$ENV_FILE"
